// <auto-generated />
using System;
using Lab10CoffeeShopRegistrationMVC.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab10CoffeeShopRegistrationMVC.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    partial class CoffeeShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lab10CoffeeShopRegistrationMVC.Models.ProductViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductViewModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductViewModelId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Lab10CoffeeShopRegistrationMVC.Models.ProductViewModel", b =>
                {
                    b.HasOne("Lab10CoffeeShopRegistrationMVC.Models.ProductViewModel", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductViewModelId");
                });

            modelBuilder.Entity("Lab10CoffeeShopRegistrationMVC.Models.ProductViewModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
